version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: stratford-music-db
    environment:
      POSTGRES_DB: stratford_music
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d stratford_music"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratford-network

  redis:
    image: redis:7-alpine
    container_name: stratford-music-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - stratford-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: stratford-music-backend
    environment:
      NODE_ENV: development
      DATABASE_URL: postgresql://postgres:password@postgres:5432/stratford_music
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-super-secret-jwt-key-dev
      PORT: 3001
      CORS_ORIGIN: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - stratford-network
    command: npm run dev

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: stratford-music-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001
      REACT_APP_ENVIRONMENT: development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - stratford-network
    command: npm start

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  stratford-network:
    driver: bridge 